### ISSUE TITLE
AttributeError: 'Real' object has no attribute 'optimize'

### ISSUE THREAD

**Issue by lsl036** [gptune/GPTune#13]
Hello! 

It seems some errors occurred when I try to run DEMO in /GPTune-Demo.
The screenshot of it is as follows: 
![image](https://user-images.githubusercontent.com/34669680/164652307-313e695c-32ab-427f-8266-129d6415dc5a.png)

Is it my compilation error or maybe there is something wrong with your code?
Looking forward to your reply, thank you. 谢谢大佬！

**Comment by liuyangzhuan** [comment]
We use patch file to modify the default scikit-optimize package, as can be seen from example build script:
https://github.com/gptune/GPTune/blob/f4512e1da3c131f5777566a72c41e7c81a28d935/config_cleanlinux.sh#L460
Make sure you have that.
