### ISSUE TITLE
Make error for pdqrdriver

### ISSUE THREAD

**Issue by akash-isu** [gptune/GPTune#14]
I'm trying the following:
`cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_COMPILER=$MPICXX -DCMAKE_C_COMPILER=$MPICC -DCMAKE_Fortran_COMPILER=$MPIF90 -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DGPTUNE_INSTALL_PATH=$SITE_PACKAGES_PATH -DTPL_BLAS_LIBRARIES="$BLAS_LIB" -DTPL_LAPACK_LIBRARIES="$LAPACK_LIB" -DTPL_SCALAPACK_LIBRARIES=$SCALAPACK_LIB`

`make`

and I run into the following error:

`[ 66%] Building Fortran object CMakeFiles/pdqrdriver.dir/examples/Scalapack-PDGEQRF/scalapack-driver/src/pmatgeninc.f.o
/usr/bin/mpif90  -I/home/akashdutta/Documents/git_repos/GPTune/gptuneclcm -I/home/akashdutta/Documents/git_repos/GPTune/examples/Scalapack-PDGEQRF/scalapack-driver/src  -fno-range-check -ffree-line-length-none -ffixed-line-length-none -fimplicit-none -lpthread -fopenmp    -c /home/akashdutta/Documents/git_repos/GPTune/examples/Scalapack-PDGEQRF/scalapack-driver/src/pmatgeninc.f -o CMakeFiles/pdqrdriver.dir/examples/Scalapack-PDGEQRF/scalapack-driver/src/pmatgeninc.f.o
make[2]: *** No rule to make target '../scalapack-2.1.0/build/install/lib/libscalapack.so', needed by 'pdqrdriver'.  Stop.
make[2]: Leaving directory '/home/akashdutta/Documents/git_repos/GPTune/build'
make[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/pdqrdriver.dir/all] Error 2
make[1]: Leaving directory '/home/akashdutta/Documents/git_repos/GPTune/build'
make: *** [Makefile:133: all] Error 2`

**Comment by liuyangzhuan** [comment]
It appears that you did not build ../scalapack-2.1.0/build/install/lib/libscalapack.so as specified by $SCALAPACK_LIB. Make sure scalapack is built there using openmpi>4.0. Here is an example of how to build it:
https://github.com/gptune/GPTune/blob/d323e969aee57045867f1523e4d12dcc671f8fc5/config_cleanlinux.sh#L201
