### ISSUE TITLE
Cannot access the historical database website. Can we have the website up? If not can we have the data available on the github?

### ISSUE THREAD

**Issue by AbrarHossainHimself** [gptune/GPTune#21]
Hello developers,
The website https://gptune.lbl.gov/docs/index.html, which hosts essential datasets for your problem is currently inaccessible. I have been trying to use your algorithm against the data, which is why I kindly request your assistance in addressing this issue. Could you please look into restoring access or provide the dataset directly on Git Hub?

**Comment by younghyunc** [comment]
Hello! Thank you for your question.

Yes, the history database website was temporarily down. We have recovered it, https://gptune.lbl.gov, and the database is now running as normal.

The specific URL https://gptune.lbl.gov/docs/index.html is for our web-version documentation for the database. The URL was temporarily disabled, but we have also re-enabled the URL. We also have a PDF-version document at https://gptune.lbl.gov/documentation/gptune-user-guide/

To navigate the datasets, you can also use our database dashboard at https://gptune.lbl.gov/repo/dashboard/

Please let us know if you have further questions!

**Comment by AbrarHossainHimself** [comment]
Thank you for the prompt support. Have a good rest of your day. :)

**Comment by AbrarHossainHimself** [comment]
Hello,
I cannot access the website again. Would you be kind enough to recheck?

**Comment by AbrarHossainHimself** [comment]
It's working again. Thank you for your support. Slightly unrelated to this topic but I had signed up and requested approval to join the site. It's been weeks and I haven't heard back yet. Will you be able to help me with that?

**Comment by younghyunc** [comment]
Thank you for your comment. Regarding the follow up question, yes, I believe we can approve your HistoryDB account soon. I will reach out to you by an email to discuss more. Sorry about the delay!

**Comment by AbrarHossainHimself** [comment]
No worries and Thank you so much for keeping my request. My email is: [abrarhossainhimself@gmail.com](abrarhossainhimself@gmail.com). This is what I used to signup for the account.
