### ISSUE TITLE
GPTune Installation Problem 

### ISSUE THREAD

**Issue by haoyunl2** [gptune/GPTune#6]
I am using NERSC Cori Supercomputer. When I try to use the script config_cori.sh to install GPTune, some modules fail to be installed, especially module GPy. The error is attached below. Then, the C compiler cannot recognize the projects in the "examples" folder. The screenshot is also attached. Could you please take a look at the issue I encounter. Thanks!

![image](https://user-images.githubusercontent.com/54645777/152851227-49de8f6d-12ab-4179-af02-783893cc4423.png)
![image](https://user-images.githubusercontent.com/54645777/152851516-2cf7da8b-1fe0-4499-93b9-7596e2a7c3d7.png)

**Comment by liuyangzhuan** [comment]
Have you changed anything of that script? 

If you add "module list" at line 256 and comment out all lines after. What does module list show you? You should have PrgEnv-gnu loaded, but apparently intel compiler is somehow still in effect.

**Comment by haoyunl2** [comment]
I have changed the python version from 3.7 to 3.8. Module list screen is attached below. PrgEnv-gnu is loaded, and PrgEnv-intel is unloaded.

![image](https://user-images.githubusercontent.com/54645777/152855784-ec183969-099b-4f93-9a6c-71cfed85be4b.png)

**Comment by younghyunc** [comment]
@liuyangzhuan, I've talked about this problem with @haoyunl2 earlier. Let me add one comment that "cori-haswell-openmpi-intel" setting works for @haoyunl2's environment, but installation fails when using "cori-haswell-openmpi-gnu". I advised @haoyunl2 to use "cori-haswell-openmpi-intel" for now, but it would be good to figure this out.

**Comment by liuyangzhuan** [comment]
@younghyunc  Thanks for the explanation. I do see there is some permission issue regarding scikit-learn and gptune installation path when using python 3.8. I made some fixes in https://github.com/gptune/GPTune/commit/67b1abb4cbd30417e5e0adf2f25a7102d278bffd
and bump the python version to 3.8.

Can you try it again? @haoyunl2

**Comment by haoyunl2** [comment]
Thanks for the reply and update. But the problem for GPy still exists. The screenshots are attached. But, I found that if I re-install the module that fails to complete when running the installation script cofig_cori.sh manually. Then the code can be run on the GNU compiler. 

![image](https://user-images.githubusercontent.com/54645777/152895321-c4b541a0-d2d3-4309-abe7-b36409afe39a.png)

![image](https://user-images.githubusercontent.com/54645777/152895382-5efbbe44-ccae-4249-8feb-ee8b168fedd7.png)

**Comment by liuyangzhuan** [comment]
Glad it worked out for you. I don't know why icc is still picked for the GPy installation. It seems that a clean rebuild fixed the problem. I will close this issue now.
