### ISSUE TITLE
Fortran compiler issue?

### ISSUE THREAD

**Issue by jeanlucf22** [gptune/GPTune#7]
I am trying to build GPTune. Very early in the build, I run into the following error message:

/usr/local/mpi2/bin/mpif90  -I/home/q8j/GIT/GPTune/gptuneclcm -I/home/q8j/GIT/GPTune/examples/Scalapack-PDGEQRF/scalapack-driver/src -fopenmp  -c /home/q8j/GIT/GPTune/examples/Scalapack-PDGEQRF/scalapack-driver/src/pdqrdriver.f -o CMakeFiles/pdqrdriver.dir/examples/Scalapack-PDGEQRF/scalapack-driver/src/pdqrdriver.f.o
/home/q8j/GIT/GPTune/examples/Scalapack-PDGEQRF/scalapack-driver/src/pdqrdriver.f:184:11:

  184 |       DO 50 CONFIG = 1, NBCONF
      |           1
Warning: Deleted feature: Loop variable at (1) must be integer
/home/q8j/GIT/GPTune/examples/Scalapack-PDGEQRF/scalapack-driver/src/pdqrdriver.f:719:72:

  719 |      $                                MEM( IPPIV ) )
      |                                                                        1
Error: Type mismatch in argument ‘ipiv’ at (1); passed REAL(8) to INTEGER(4)

I am not a Fortran programmer... Could it be a Fortran compiler issue? I am using GNU Fortran (GCC) 11.2.0.

**Comment by liuyangzhuan** [comment]
Hi, @jeanlucf22, the error is a known issue for compiling fortran files with GCC>=10, adding "-fallow-argument-mismatch" fixes it. I've pushed some changes, can you try this commit:
c79f64a7a7286002ad79f3ab42d2b6b963c199f8

**Comment by jeanlucf22** [comment]
Yes, the latest commit allows me to compile that file (with just a warning, which I assume is ok). Thanks!
